import Head from 'next/head';
import Link from 'next/link'; // Import Link from next/link
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>

        {/* 2x2 Grid of Emojis */}
        <div style={{ display: 'grid', gridTemplateColumns: 'auto auto', gap: '10px', justifyContent: 'center' }}>
          <div style={{ fontSize: '80px' }}>🌟</div>
          <div style={{ fontSize: '80px' }}>🚀</div>
          <Link href="/Sleep"> {/* Link to Sleep.js */}
            <a style={{ fontSize: '80px', cursor: 'pointer' }}>😴</a>
          </Link>
          <Link href="/Water"> {/* Link to Water.js */}
            <a style={{ fontSize: '80px', cursor: 'pointer' }}>🚰</a>
          </Link>
        </div>
      </main>
    </>
  );
}
